// Generated by https://quicktype.io, extensión que consiste en tipar peticiones para agilizar el trabajo con typescript

export interface ClientesType {
    nombre:   string;
    empresa:  string;
    email:    string;
    telefono: string;
    notas:    string;
    id:       number;
}