// Generated by https://quicktype.io

export interface ClientesType {
    nombre:   string;
    empresa:  string;
    email:    string;
    telefono: string;
    notas:    string;
    id:       number;
}
